services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careerbridge-frontend
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careerbridge-backend
    ports:
      - "5000:5000"